### ISSUE TITLE
Extension installed but not open

### ISSUE THREAD

**Issue by ananprara** [microsoft/vscode-azure-account#941] opened 2024-04-01 05:22 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

**Comment by alexweininger** [comment] 2024-04-03 17:59
Closing as a duplicate of https://github.com/microsoft/vscode-node-azure-pack/issues/61

**Closed by alexweininger** 2024-04-03 17:59 UTC
