### ISSUE TITLE
Azure sign in stuck on loading

### ISSUE THREAD

**Issue by JiheHe** [microsoft/vscode-azure-account#487] opened 2022-02-27 07:02 UTC
Does this occur consistently? 
Repro steps:

1. Can't sign in on VS code azure, permanently stuck
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment] 2022-02-28 18:27
Thanks for filing, @JiheHe. Please follow these instructions to download a private build and let's see if that fixes the issue.

1. Download version `v0.10.1-alpha` of the extension [here](https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/43867/artifacts?artifactName=vsix&api-version=7.0&%24format=zip).
2. Open VS Code and run the `Extensions: Install Specific Version of Extension...` command (accessible from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)).
![Screen Shot 2022-02-28 at 10 19 15 AM](https://user-images.githubusercontent.com/22795803/156036649-2f02c066-7e89-470c-8300-1903fe16f563.png)
3. In the file picker: browse to the `.vsix` file you downloaded and select it.
4. After selecting the file, a notification should appear prompting you to reaload the VS Code window. Click "Reload Now".
![Screen Shot 2022-02-28 at 10 21 37 AM](https://user-images.githubusercontent.com/22795803/156037095-0e4830ed-f226-48d6-9bbd-1e2cbde08029.png)
5. Open the marketplace in VS Code. Verify that the Azure Account Extension version reads `v0.10.1-alpha`.
![Screen Shot 2022-02-28 at 10 23 32 AM](https://user-images.githubusercontent.com/22795803/156037379-8d6c1d6a-8ea6-428f-8fb8-8ca5446b7a5c.png)
7. Try signing in again and let us know if you still run into the "Timeout waiting for code" error.

**Comment by wwlorey** [comment] 2022-02-28 18:29
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/442

**Closed** 2022-07-25 18:03 UTC
Labels: duplicate, info-needed
