### ISSUE TITLE
UNIX[No such file or directory]

### ISSUE THREAD

**Issue by aakinlalu** [microsoft/vscode-azure-account#735] opened 2023-03-14 01:39 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.3
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

**Comment by alexweininger** [comment] 2023-03-14 19:55
Closing as duplicate of #614, please follow that issue.

**Closed by alexweininger** 2023-03-14 19:55 UTC
