### ISSUE TITLE
Unable to login to azure from VS code

### ISSUE THREAD

**Issue by pawankumar-stack** [microsoft/vscode-azure-account#553] opened 2022-04-21 04:34 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.loginToCloud
Error type: Error
Error Message: No response from the server

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:799923
extension.bundle.js:2:812956extension.bundle.js:2:812956
```

</details>

**Comment by wwlorey** [comment] 2022-04-21 17:18
Thanks for filing, @pawankumar-stack. Please see https://github.com/microsoft/vscode-azure-account/issues/550#issuecomment-1105482177 for guidance and please add any more info you may have on that issue.

It's also possible that the login service or our redirect server was temporarily down.

Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/550.

**Closed by wwlorey** 2022-04-21 17:18 UTC
