### ISSUE TITLE
There is an Error in vscode

### ISSUE THREAD

**Issue by vidigummy** [microsoft/vscode-azure-account#618] opened 2022-08-15 04:22 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.1
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.70.1
Language: ko

**Comment by alexweininger** [comment] 2022-11-30 23:32
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/614

**Closed by alexweininger** 2022-11-30 23:32 UTC
