### ISSUE TITLE
Cannot sign in to Azure Account

### ISSUE THREAD

**Issue by duselbaer** [microsoft/vscode-azure-account#494] opened 2022-03-02 07:18 UTC
Does this occur consistently? YES
Repro steps:

1. Select "Azure: Sign in"
2. Browser opens - I select the account where I am currently logged in3. 
3. Error dialog appears 

Action: azure-account.login
Error type: invalid_grant
Error Message: invalid_grant: redacted:id - [redacted:id redacted:id47Z]: AADSTS500202: User account '{EmailHidden}' from external identity provider redacted:url is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id47Z - Correlation ID: redacted:id - Trace ID: redacted:id

Version: 0.10.0
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.65.0-insider
Language: de

<details>
<summary>Call Stack</summary>

```
ServerError.AuthError [as constructor] extension.bundle.js:2:154585
new ServerError extension.bundle.js:2:210448
ResponseHandler.validateTokenResponse extension.bundle.js:2:229292
AuthorizationCodeClient.<anonymous> extension.bundle.js:2:235023
step extension.bundle.js:2:147853
Object.next extension.bundle.js:2:147958
fulfilled extension.bundle.js:2:146622
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by duselbaer** [comment] 2022-03-02 07:23
With "normal" Visual Code - that one works for me - so really no high priority

**Comment by wwlorey** [comment] 2022-03-02 19:31
Thanks for filing, @duselbaer. 

Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/446. Please see https://github.com/microsoft/vscode-azure-account/issues/446#issuecomment-1042243436 for why this error is happening & the workaround for it.

**Closed by wwlorey** 2022-03-02 19:31 UTC
