### ISSUE TITLE
Latest v0.12.0 Release Is Broken by Dependency Loops

### ISSUE THREAD

**Issue by MBR41** [microsoft/vscode-azure-account#966] opened 2024-05-15 01:38 UTC
Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z (9 mos ago)
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.5.0

Are you connected to a proxy server? No

Steps to Reproduce:

1. Install vscode fresh with no extensions
2. Install the Azure Accounts extension
3. The error `The following extensions contain dependency loops and have been disabled: 'ms-azuretools.vscode-azureresourcegroups', 'ms-vscode.azure-account'` appears and both extensions are disabled. The extensions cannot be uninstalled either as they depend on each other.

Workaround:
- Revert to `v0.11.7`

![Screenshot 2024-05-15 at 11 37 19 AM](https://github.com/microsoft/vscode-azure-account/assets/146045191/2addc3af-eaae-49cb-aa55-978b0ede186d)

**Comment by alexweininger** [comment] 2024-05-15 03:14
Hi @MBR41, I'm unable to reproduce this error. Can you please try again? The only thing I can think that might cause this is if an older version of the Azure Resources extension is being installed that still depends on Azure Account. Can you make sure the Azure Resources extension is updated to the latest version (v0.9.0)?


<img width="528" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/12476526/e0e5ec29-a7c4-479a-b101-c6c63214d882">

With the latest versions of each extension, the only dependencies are that Azure Account depends on Azure Resources.

**Comment by MBR41** [comment] 2024-05-15 03:46
Hi @alexweininger thank you for the response. I tried again and can still reproduce the error. Azure Resources `0.7.5` is installed automatically when Azure Account is installed.

I don't have the option to install `0.9.0`:

![Screenshot 2024-05-15 at 1 46 12 PM](https://github.com/microsoft/vscode-azure-account/assets/146045191/12b671b0-cbee-44e2-91fe-dc0c393156dc)

**Comment by alexweininger** [comment] 2024-05-15 03:50
> I don't have the option to install `0.9.0`:
> 
> ![Screenshot 2024-05-15 at 1 46 12 PM](https://private-user-images.githubusercontent.com/146045191/330653802-12b671b0-cbee-44e2-91fe-dc0c393156dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDUxOTYsIm5iZiI6MTcxNTc0NDg5NiwicGF0aCI6Ii8xNDYwNDUxOTEvMzMwNjUzODAyLTEyYjY3MWIwLWNiZWUtNDRlMi05MWZlLWRjMGMzOTMxNTZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwMzQ4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2ViMjNkMzE2MjNkNGQxZDkxYzg5NzhiNzFhZjMyZDYzYWQ3MTAzOWZhYzA3ZDQ1MWU1Zjk5OTFhOGNlNmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.16nsnzuJRH7dQWrhp8HNx7ypltQR0psql1otJG2KUVo)

Oh, I just noticed you're on [v1.80 of VS Code from June of last year](https://code.visualstudio.com/updates/v1_80). I believe the issue will be fixed if you update VS Code to a newer version. Could you try updating to the latest version and try again?

**Comment by aedans-womp** [comment] 2024-05-15 17:38
Updating to vscode v1.89 fixed the issue, but it was rather frustrating to wake up to find that all of my azure extensions were disabled and I couldn't uninstall azure account or azure resources due to circular dependencies.

**Comment by alexweininger** [comment] 2024-05-15 17:40
> Updating to vscode v1.89 fixed the issue for me, but it was rather frustrating to wake up to find that all of my azure extensions were disabled and I couldn't uninstall azure account or azure resources due to circular dependencies.

Sorry about that. We are deprecating Azure Account and need a way to migrate users to Azure Resources.

**Comment by MBR41** [comment] 2024-05-16 03:01
> Sorry about that. We are deprecating Azure Account and need a way to migrate users to Azure Resources.

I've updated vscode to `1.89.1`, should I uninstall Azure Account now?

**Comment by alexweininger** [comment] 2024-05-16 03:09
> Should I uninstall Azure Account now?

Yes please! If you don't have any extensions that still depend on Azure Accounts, then uninstall it.

**Closed** 2024-06-27 19:32 UTC
