### ISSUE TITLE
Clicking Sign in to Azure does nothing

### ISSUE THREAD

**Issue by craigjar** [Microsoft/vscode-azure-account#112] opened 2018-11-20 17:58 UTC
When clicking the "Sign in to Azure..." it changes to "Waiting for Azure Sign-in..." for a second, then switches back.  Nothing else happens and no error message is received.  Note that I am behind a corporate proxy which may be causing issues.

![image](https://user-images.githubusercontent.com/13706803/48792908-73c70200-ecc3-11e8-8cba-275fb35f4ace.png)

![image](https://user-images.githubusercontent.com/13706803/48792934-84777800-ecc3-11e8-80e1-70bb73f62022.png)

**Comment by chrmarti** [comment] 2018-11-21 20:51
@craigjar I'm adding some logging to the Insiders build. Maybe you can help me out tracking this down by checking your logs in that. I'll let you know when that build out.

**Comment by chrmarti** [comment] 2018-11-22 07:42
@craigjar Could you try signing in with the latest insiders build and check what log `ProxyResolver#resolveProxy` entries you get in the Extension Host log:
![image](https://user-images.githubusercontent.com/9205389/48888140-fa99ed00-ee31-11e8-9391-a7b5754d866b.png)

Your entries will likely show something different than `DIRECT` at the end. Let me know what that is. If that includes any sensitive information, maybe replacing each letter with x and each digit with 1 will remove the sensitive information, but retain the structural information I'm interested in.

**Comment by craigjar** [comment] 2018-11-26 13:39
@chrmarti I tried using the latest Insiders version this morning and not able to get the log output you expect.  Let me know if there is anything else I need to do.

![image](https://user-images.githubusercontent.com/13706803/49017292-7fe51080-f156-11e8-85d7-e1871ce034ea.png)

My version:
![image](https://user-images.githubusercontent.com/13706803/49017317-968b6780-f156-11e8-8fa7-14053fd9f3e5.png)

Proxy env vars:
![image](https://user-images.githubusercontent.com/13706803/49017341-a0ad6600-f156-11e8-84d0-f824b0c302c7.png)

**Comment by chrmarti** [comment] 2018-11-26 16:10
@craigjar Todays build needs to be started with `code-insiders --log debug` to show these entries. (That avoids filling the log with too much information.)

**Comment by andrej2704** [comment] 2018-11-29 22:55
I don't have any proxy. But after upgrade can't login into azure. Version 1.29.1 (1.29.1).

Steps: 
1. Click Sign-in to Azure
2. Click on the popup to copy & open
3. Insert the code and submit in the browser
4. Return to the VS Code
5. Observe spinner and 'Waiting for Azure sign-in' and nothing happens.

**Comment by arcooke** [comment] 2018-12-05 19:55
I'm having the same issues on linux (KDE Neon/Ubuntu 18.04).  I am not behind any proxies or corporate networks/firewalls.  I'm at home plugged into a standard home router with no tunneling. 

I launched vscode with `code-insiders --log debug`.  

Some text shows in the vsc console when I start the program, but after running through the entire Azure sign-in procedure, nothing extra is added to my console with log level set to debug.

```
[2018-12-05 13:34:06.912] [exthost] [info] extension host started
[2018-12-05 13:34:06.919] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:06.919] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code-insiders/resources/app/extensions/debug-auto-launch/dist/extension
[2018-12-05 13:34:06.921] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:06.921] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code-insiders/resources/app/extensions/emmet/dist/extension
[2018-12-05 13:34:06.933] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:06.933] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code-insiders/resources/app/extensions/git/dist/main
[2018-12-05 13:34:06.986] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:06.986] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code-insiders/resources/app/extensions/merge-conflict/dist/extension
[2018-12-05 13:34:06.989] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.azure-account {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:06.989] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/ms-vscode.azure-account-0.7.0/dist/extension
[2018-12-05 13:34:07.195] [exthost] [info] eager extensions activated
[2018-12-05 13:34:07.245] [exthost] [info] ExtensionService#_doActivateExtension vsciot-vscode.azure-iot-toolkit {"startup":true,"activationEvent":"*"}
[2018-12-05 13:34:07.245] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/vsciot-vscode.azure-iot-toolkit-1.7.0/out/src/extension
[2018-12-05 13:34:15.602] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azureappservice {"startup":false,"activationEvent":"onView:azureAppService"}
[2018-12-05 13:34:15.602] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/ms-azuretools.vscode-azureappservice-0.10.0/out/src/extension
[2018-12-05 13:34:16.470] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurefunctions {"startup":false,"activationEvent":"onView:azureFunctionsExplorer"}
[2018-12-05 13:34:16.470] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/ms-azuretools.vscode-azurefunctions-0.13.0/out/src/extension
[2018-12-05 13:34:17.569] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurestorage {"startup":false,"activationEvent":"onView:azureStorage"}
[2018-12-05 13:34:17.569] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/ms-azuretools.vscode-azurestorage-0.4.2/out/src/extension
[2018-12-05 13:34:17.952] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-cosmosdb {"startup":false,"activationEvent":"onView:cosmosDBExplorer"}
[2018-12-05 13:34:17.952] [exthost] [info] ExtensionService#loadCommonJSModule /home/adam/.vscode-insiders/extensions/ms-azuretools.vscode-cosmosdb-0.9.1/out/src/extension
```

Similar errors that @craigjar was having in the developer tools console.

![image](https://user-images.githubusercontent.com/6278400/49539416-381b6300-f893-11e8-9be4-59ea44890782.png)

---

Running `code-insiders --verbose`

Terminal output (below output started after launching browser to sign in):

```
[main 1:45:04 PM] windowsService#openExternal
Icon theme "gnome" not found.
[main 1:45:08 PM] update#checkForUpdates, state =  idle
[main 1:45:08 PM] update#setState checking for updates
[main 1:45:08 PM] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/insider/85f805acf9436381b878cab5ab6c5146beec7893
[main 1:45:08 PM] update#setState idle
[main 1:45:08 PM] telemetry/update:notAvailable { explicit: false }
[25598:1205/134602.411188:INFO:CONSOLE(303)] "%c[Extension Host] %cError: The name org.freedesktop.secrets was not provided by any .service files %c(at <anonymous>)", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (303)
[25598:1205/134602.508219:INFO:CONSOLE(3265)] "Extension Host", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3265)
[25598:1205/134602.508249:INFO:CONSOLE(3265)] "%c** Message: 13:46:02.407: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3265)
[25598:1205/134602.508278:INFO:CONSOLE(3265)] "console.groupEnd", source: file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js (3265)

```

**Comment by craigjar** [comment] 2018-12-06 13:19
@chrmarti Hi Christof,

I tried again with HTTP[S]_PROXY environment variables set and the `code-insiders --log debug`.  

```
>env|grep -i proxy
HTTPS_PROXY=http://localhost:3128
HTTP_PROXY=http://localhost:3128
```

Here are my VS Code proxy settings:
![image](https://user-images.githubusercontent.com/13706803/49585765-4b7b0c80-f92d-11e8-9dcf-e8d4aeff3047.png)

```
[2018-12-06 07:55:48.288] [exthost] [debug] ProxyResolver#resolveProxy http://localhost:3128/https://dc.services.visualstudio.com/api/profiles/AIF-[profile-id]/appId DIRECT
[2018-12-06 07:56:25.087] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.azure-account {"startup":false,"activationEvent":"onView:cosmosDBExplorer"}
[2018-12-06 07:56:25.087] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\myuser\.vscode-insiders\extensions\ms-vscode.azure-account-0.7.0\dist\extension
[2018-12-06 07:56:26.344] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-cosmosdb {"startup":false,"activationEvent":"onView:cosmosDBExplorer"}
[2018-12-06 07:56:26.344] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\myuser\.vscode-insiders\extensions\ms-azuretools.vscode-cosmosdb-0.9.0\out\src\extension
[2018-12-06 07:56:41.528] [exthost] [debug] ProxyResolver#resolveProxy https://login.microsoftonline.com/common/oauth2/token?api-version=1.0 PROXY corpproxy5.net.ca.mycompany.com:8080;PROXY corpproxy4.net.ca.mycompany.com:8080;PROXY corpproxy3.net.ca.mycompany.com:8080;PROXY cbpcamamc02ic.net.ca.mycompany.com:8080;PROXY corpproxy.net.ca.mycompany.com:8080;PROXY corpproxy2.net.ca.mycompany.com:8080;DIRECT
[2018-12-06 07:56:56.289] [exthost] [debug] ProxyResolver#resolveProxy http://localhost:3128/https://vortex.data.microsoft.com/collect/v1 DIRECT
[2018-12-06 07:57:09.736] [exthost] [debug] ProxyResolver#resolveProxy https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0 PROXY corpproxy5.net.ca.mycompany.com:8080;PROXY corpproxy4.net.ca.mycompany.com:8080;PROXY corpproxy3.net.ca.mycompany.com:8080;PROXY cbpcamamc02ic.net.ca.mycompany.com:8080;PROXY corpproxy.net.ca.mycompany.com:8080;PROXY corpproxy2.net.ca.mycompany.com:8080;DIRECT
```

Turning off the experimental proxy support didn't make much difference.  After restarting VS Code Insiders it updated to a newer version and I no longer see the debug statements.

So, for my case I see a mix of some requests using my local CNTLM proxy which doesn't require NTLM authentication, and then some requests using the corporate proxy which does require NTLM authentication.  Issue seems to be inconsistencies in controlling which proxy to use, as well as lack of NTLM authentication support.

**Comment by chrmarti** [comment] 2018-12-06 15:11
@craigjar That's an interesting case, we don't support that "out-of-the-box" yet. What you can do:
- Set the Http: Proxy setting to your localhost proxy. And:
- Set the Http: Proxy Support to 'override'. (This is the System Proxy setting with a new name.)

**Comment by bit-pirate** [comment] 2019-03-09 20:52
Hi there,
running on (K)Ubuntu 18.04 I solved this issue for me by install `gnome-keyring`.

Another issue with same error ("Error: The name org.freedesktop.secrets was not provided by any .service files") message led me to this solution: https://github.com/Foundry376/Mailspring/issues/681

**Comment by chrmarti** [comment] 2019-03-13 15:58
Closing as duplicate of the NTLM support in #124.

**Closed by chrmarti** 2019-03-13 15:58 UTC
Labels: bug
