### ISSUE TITLE
When attempting to open Bash in Cloud Shell, the "Select Directory" box is always blank

### ISSUE THREAD

**Issue by robm82** [microsoft/vscode-azure-account#229] opened 2020-09-22 07:43 UTC
Issue Type: <b>Bug</b>

1. I can sign in to my Azure Account without any issues
2. In the command palette, when I type "Azure: Open Bash in Cloud Shell", it displays another box over the command palette asking to "Select directory"
3. But the "Select directory" box is blank, and won't let me select anything

![image](https://user-images.githubusercontent.com/47445676/93855622-aff88e80-fcaf-11ea-949e-d1cb33e54cef.png)

Extension version: 0.9.3
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (22.84GB free)|
|Process Argv|--remote=wsl+Ubuntu-20.04 --crash-reporter-id 5cc6be51-a125-42ee-8b56-970eb95a2a32|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.92GB (24.67GB free)|
|VM|0%|
</details>

**Comment by robm82** [comment] 2020-09-22 07:55
I can confirm that rolling back the extension to 0.8.11 has fixed the issue, so there must have been an update since then that breaks this functionality.

**Comment by RMacfarlane** [comment] 2020-09-22 14:47
Thanks @robm82, this looks like a duplicate of https://github.com/microsoft/vscode-azure-account/issues/220, so I'm going to go ahead and close this

**Closed by RMacfarlane** 2020-09-22 14:47 UTC
