### ISSUE TITLE
wont sign into azure

### ISSUE THREAD

**Issue by zape78** [microsoft/vscode-azure-account#671] opened 2022-11-21 04:08 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.2
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

**Comment by alexweininger** [comment] 2022-11-30 23:32
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/614

**Closed by alexweininger** 2022-11-30 23:32 UTC
