### ISSUE TITLE
Logging into azure with Azure account extenion goes to localhost

### ISSUE THREAD

**Issue by pcreehan** [microsoft/vscode-azure-account#263] opened 2021-05-04 11:20 UTC
Issue Type: <b>Bug</b>

I'm not sure what changed (sorry), but something I must have installed or done recently seems to have made it so when I try to log in, the extension will open up a web browser but instead of going to login.microsoftonline.com, it goes to localhost:__[some random port, different every time]__.

Extension version: 0.9.8
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.21370

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.25GB free)|
|Process Argv|--crash-reporter-id 793be466-1136-444f-84ad-03e61fb7f44b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscus158:30286553

```

</details>

**Comment by wwlorey** [comment] 2021-06-07 18:55
Hi @pcreehan, localhost should redirect you to login.microsoftonline.com to complete the sign-in process. Is it hanging at localhost for you?

**Comment by pcreehan** [comment] 2021-07-01 01:23
Apologize to the delay. Yes, it opens a new browser window to localhost at some random port (different every time) and then stop with an SSL error:
![image](https://user-images.githubusercontent.com/8560828/124050664-fcb08900-d9e8-11eb-8ebe-1780725854df.png)

![image](https://user-images.githubusercontent.com/8560828/124050652-f4f0e480-d9e8-11eb-8880-1bc6f35d1cc8.png)

![image](https://user-images.githubusercontent.com/8560828/124050823-4c8f5000-d9e9-11eb-9c8c-fad07fb7325b.png)

**Comment by wwlorey** [comment] 2021-07-06 17:47
That's strange - I'm not able to reproduce the SSL error on Edge or Brave. 

Is there anything in particular about your setup that might cause this (perhaps being behind a proxy)? And can you verify you get the same problem in another browser?

**Comment by pcreehan** [comment] 2021-07-07 19:59
I got the same problem after switching browser default. I ran netstat to see what ports were listening and I could see the port it was trying to open (good), but I saw a bunch of kubernetes opened ports too, so I went and uninstalled a kubernetes extension and a docker extension and an AKS extension and now the Azure Account extension works. Not sure which of the 3 it was that was creating the problem. Maybe I'll try adding them back and see when it breaks.

**Comment by pcreehan** [comment] 2021-07-07 20:07
Nope - I lied. It seems it actually was the browser switch that did it. Edge (dev channel) doesn't work, Chrome works and Edge (non-dev channel) works. I have no idea what's causing it, but at least I have a workaround.

From: Patrick Creehan
Sent: Wednesday, July 7, 2021 3:59 PM
To: microsoft/vscode-azure-account ***@***.***>; microsoft/vscode-azure-account ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoft/vscode-azure-account] Logging into azure with Azure account extenion goes to localhost (#263)

I got the same problem after switching browser default. I ran netstat to see what ports were listening and I could see the port it was trying to open (good), but I saw a bunch of kubernetes opened ports too, so I went and uninstalled a kubernetes extension and a docker extension and an AKS extension and now the Azure Account extension works. Not sure which of the 3 it was that was creating the problem. Maybe I'll try adding them back and see when it breaks.

**Comment by wwlorey** [comment] 2021-07-07 20:30
> Nope - I lied. It seems it actually was the browser switch that did it. Edge (dev channel) doesn't work, Chrome works and Edge (non-dev channel) works. I have no idea what's causing it, but at least I have a workaround.

Glad to hear you were able to work around the problem. Closing this since it's a problem with Edge's dev version

**Closed by wwlorey** 2021-07-07 20:30 UTC
Labels: needs more info
