### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by waleakomolafe** [microsoft/vscode-azure-account#460] opened 2022-02-18 05:36 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.login
Error type: Error
Error Message: Timeout waiting for code

Version: 0.10.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout.<anonymous> extension.bundle.js:2:2321688
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by wwlorey** [comment] 2022-02-18 17:55
Thanks for filing, @waleakomolafe.

Does your web browser open and present the login window when you execute the `Azure: Sign In` command? Or is this error thrown immediately?

Can you successfully sign in using the `Azure: Sign In with Device Code` command?

Did you set your `Azure: Tenant` setting?

Also - what are the values of your `Azure: Authentication Library` and `Azure: Cloud` settings?

**Comment by waleakomolafe** [comment] 2022-02-18 19:11
Using the sign In command the login window opens and throws the error (Sorry we are unable to sign you in, and I cant even paste the tenant ID into the block)
Using the sign In with device Code throws the error (Acquiring user code failed)
I can set azure tenant setting, once the browser opens the field is locked with the error message (Sorry we are unable to sign you in)
Where do I set the authentication library and cloud setting. Your help will be appreciated

**Comment by wwlorey** [comment] 2022-02-25 19:39
Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/442.

@waleakomolafe if you have more info to provide please do so in the linked issue.

**Closed by wwlorey** 2022-02-25 19:39 UTC
Labels: needs more info
