### ISSUE TITLE
I sign in successfully but the extension does not find any of my subscriptions

### ISSUE THREAD

**Issue by plachmann** [microsoft/vscode-azure-account#193] opened 2020-06-08 18:07 UTC
I am using VS Code on Windows version 1.45.1
I am using the Azure Functions extension version 0.22.1

![image](https://user-images.githubusercontent.com/16654047/84064500-b1b47580-a990-11ea-9aaa-db4bc2a38f23.png)

I can sign in successfully. And I see this

![image](https://user-images.githubusercontent.com/16654047/84064594-dd376000-a990-11ea-86ce-9fca6bbbf407.png)

Then if I try to select a subscription I always get this:

![image](https://user-images.githubusercontent.com/16654047/84064656-fe984c00-a990-11ea-98f7-1c040abd4a9e.png)

If I go to a power shell prompt and issue the command 'az account list' I can see all 4 of the subscriptions I have access to (1 for my free account, 3 for my client)

Is there a workaround for this issue?

**Comment by plachmann** [comment] 2020-06-08 18:35
Azure Account extension version 0.8.11

**Comment by dim-0** [comment] 2020-06-09 21:08
I have the exact same issue in https://github.com/microsoft/vscode-azure-account/issues/195 and therefore close it again.
Purging the install, deleting user config and extensions (~/.vscode/ and ~/.config/Code/) and reinstalling did not work.

**Comment by dim-0** [comment] 2020-06-14 15:48
I find it pretty upsetting to see no activity on this, even though this is an integral part of an official Microsoft product. Seriously makes me wonder, whether I want to keep working with Azure, if the _account management_ part of their reference IDE sees so little support activity... (not that Azure's regular customer support helped me any further so far)

One more piece of information: This issue persists, even if I do a clean install of VSCode to a different machine.

**Comment by chrmarti** [comment] 2020-06-15 08:12
Try setting the tenant id of your subscriptions in the settings:
![image](https://user-images.githubusercontent.com/9205389/84633276-7239dc00-aef0-11ea-9d2f-ced6127844c5.png)

We usually discover all tenants, but not all are necessarily listed.

Does that help?

**Comment by dim-0** [comment] 2020-06-17 16:50
Hi @chrmarti,
indeed, this worked. Thanks a lot!

**Closed** 2020-06-22 17:19 UTC

**Comment by janielMartell** [comment] 2020-07-23 15:41
Any time I try to see my logic apps from vscode it shows the following error: "The subscription 'MY_SUB_ID' could not be found." 
My resources are in a sovereign cloud, I configured in the Azure: Cloud and I also added the The Azure: Tenant, and it still does not work for me. Any thoughts?

**Comment by RMacfarlane** [comment] 2020-07-23 15:43
@janielMartell Does running the command `Azure: Select Subscriptions` show a list with your subscription in it?

**Comment by janielMartell** [comment] 2020-07-23 15:45
@RMacfarlane Yes, when I run that command my subscription appears, and it's selected.

**Comment by RMacfarlane** [comment] 2020-07-23 15:49
@janielMartell Then I suspect the problem is with the logic apps extension, can you open a new issue there?

**Comment by merrellsj** [comment] 2020-08-01 09:18
Same exact issue with Azure sovereign cloud, any solutions?

**Comment by janielMartell** [comment] 2020-08-01 16:05
For anyone that might be interested, I opened an issue with the logic app team (As advised by @RMacfarlane). And they told me that they don’t support sovereign clouds yet, but there’s a PR so we should have support relatively soon 👍 

https://github.com/microsoft/vscode-azurelogicapps/issues/165#issuecomment-666540696

**Comment by mhoeger** [comment] 2021-02-10 18:58
@chrmarti - is there a longer-term fix being tracked that's not a manual workaround? Or some sort of error that can be surfaced when fetching tenant fails? I just ran into this today. Thanks!

**Comment by andrews05** [comment] 2021-09-13 23:04
I had to do the same thing. I was on a free trial and it was working but after upgrading I stopped working until I set my tenant id in the settings. Isn't this a bug? It should work without having to do that.

**Comment by chrmarti** [comment] 2021-09-15 12:24
@andrews05 Could you open a new issue for this? Thanks.

**Comment by Sidzeppelin95** [comment] 2024-01-04 12:03
I am facing the same issue, even after installing the proxy extension and restarting the vs code application. I get a network error after signing in to my azure account via vs code and am unable to select subscription.
