### ISSUE TITLE
VS Code Azure sign in don't work

### ISSUE THREAD

**Issue by tumelhar** [microsoft/vscode-azure-account#199] opened 2020-06-26 12:50 UTC
Azure sign in don' work. Exits after time-out. No proxy.
After Azure sign in command, VS Code spawns default browser with url 'localhost:xxxx/signin?nonce=xxxxxxxxx=='
Browser waits for server, but extensionHost newer answer. Sign in fails after timeout.

$ lsof  -i 4
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
code     7661 xxxxx   56u  IPv4 253260      0t0  TCP localhost:39559->localhost:38808 (ESTABLISHED)
code     7661 xxxxx   58u  IPv4 251047      0t0  TCP localhost:39559 (LISTEN)
code     7661 xxxxx   63u  IPv4 252535      0t0  TCP localhost:39559->localhost:38812 (ESTABLISHED)
firefox 29845 xxxxx  171u  IPv4 252497      0t0  TCP localhost:38808->localhost:39559 (ESTABLISHED)

PID 7661    /usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost

VS Code
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.18-200.fc31.x86_64

VS Code Extensions
Azure Account 0.8.11
Azure Functions 0.22.1
Azure Storage 0.9.0

Host
Fedora 31 5.6.18-200.fc31.x86_64   (Inside VirtualBox 6.1.8, behind NAT)

Browser
Firefox 77.0.1 (64-bit)

**Comment by tumelhar** [comment] 2020-06-26 13:33
In addition, I also have Azure CLI Tools 0.5.0 extension added and azure-cli npm package installed.
Shell command line 'az login' works fine.

**Comment by jungaretti** [comment] 2020-09-22 01:45
This looks like the same bug as #179

**Comment by wwlorey** [comment] 2021-07-08 23:50
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/179

**Closed by wwlorey** 2021-07-08 23:50 UTC
