### ISSUE TITLE
Azure Sign In hangs forever

### ISSUE THREAD

**Issue by pmozbert** [microsoft/vscode-azure-account#173] opened 2020-03-18 00:06 UTC
Issue Type: <b>Bug</b>

I am behind a corporate web proxy.  That's probably the cause.  To reproduce
1: be behind a proxy that requires authentication
2: Run Azure: Sign In from the commanded palette.

The bottom status bar shows the message "Azure: Signing In..."

Extension version: 0.8.8
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by wwlorey** [comment] 2021-07-09 22:01
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/179

**Closed by wwlorey** 2021-07-09 22:01 UTC
