### ISSUE TITLE
Can not login to azure clouds

### ISSUE THREAD

**Issue by lcharanteja** [microsoft/vscode-azure-account#223] opened 2020-09-10 15:46 UTC
When tried to login to azure cloud, previously extension used to list the clouds to select from.
But it doesn't show any list to select. Stuck at  "_Choose cloud to sign in to_".

![image](https://user-images.githubusercontent.com/9964952/92757992-4d70cb80-f35c-11ea-8755-73b50f552c81.png)

Developer tools have below error when tried to sign in to cloud.
  ```
ERR Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:536:254
    at Array.map (<anonymous>)
    at E.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:536:207)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:556:756
    at t.EventBufferer.bufferEvents (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at A.splice (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:556:723)
    at x.setElements (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1168:909)
    at E.update (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1186:643)
    at E.set items [as items] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1179:540)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1197:369
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by RMacfarlane** [comment] 2020-09-11 03:09
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/216, this should be fixed in version 0.9.3, which was just published. Thanks!

**Closed by RMacfarlane** 2020-09-11 03:09 UTC
