### ISSUE TITLE
Azure Login Doesn't work on Mac

### ISSUE THREAD

**Issue by VickiFu** [Microsoft/vscode-azure-account#37] opened 2018-02-05 04:20 UTC
I had tried many times to get link and paste the code. But the azure login never get through on Mac.

**Comment by chrisdias** [comment] 2018-02-05 04:38
Hi, sorry about this. Some questions:

- what happens, how do you know it's not working?  If you open the chrome developer tools (Help -> Developer Tools) do you see any errors in the console?
- if you try from Windows/Linux does it work?  
- Can you log in to the Azure portal through the browser directly?

**Comment by NewGyu** [comment] 2018-02-07 08:09
Me too.

1. `Command+Shift + P` 
2. `Azure: Open Bash in Cloud Shell`

```
Requesting a Cloud Shell...
Connecting terminal...
Warning: Failed to mount the Azure file share. Your cloud drive won't be available.
Your Cloud Shell session will be ephemeral so no files or system changes will persist beyond your current session.
newgyu@Azure:~$
```

Launched cloud-shell cannot mount `~/clouddrive`.
When I launch cloud-shell with using the Azure portal , it could mount `~/clouddrive`.

I'm using MacOS Sierra and VSCode 1.19.3.

**Comment by chrmarti** [comment] 2018-02-07 08:20
@jluk What might cause the failure to mount the Azure file share? Is this something we might cause on the VS Code extension's side?

**Comment by jluk** [comment] 2018-02-07 17:57
@chrmarti Not sure, we'd need some more info. To start @NewGyu could you share your Azure email used to login? We can look at some traces to see what happened during the mount operation which will help us see if this was a storage, cloud shell, or vs code implementation issue.

**Comment by NewGyu** [comment] 2018-02-08 02:40
@jluk Sorry, I cannot share `Azure email`. Because I'm using my company account that is not personal account.

Will not this phenomenon be reproduced in your Azure subscription?

**Comment by jluk** [comment] 2018-02-08 17:03
@NewGyu no problem, failed mounting can occur for a few reasons that are unique per user and our service has no existing mounting issues that we know of. Are you still seeing this issue, if so do you see this file mounting error when you try to access from shell.azure.com?

**Comment by NewGyu** [comment] 2018-02-09 03:22
@jluk Sorry, it seems that the cause was in my Azure environment.
I tried to reproduce today, but it was not reproduced.

I do not really understand the true cause, but it is certain that it was not a problem with this wonderful `vscode-azure-account`.

**Comment by jluk** [comment] 2018-02-09 18:21
@NewGyu Sounds like it could have been an ad-hoc Azure storage failed operation, glad to see it resolved now! Happy to see this vscode extension is helping you out though 😄

**Comment by chrmarti** [comment] 2018-03-07 14:02
Closing since this seems to be resolved.

**Closed by chrmarti** 2018-03-07 14:02 UTC
