### ISSUE TITLE
You appear to be offline. Please check your network connection.

### ISSUE THREAD

**Issue by SujjithS** [microsoft/vscode-azure-account#745] opened 2023-03-22 12:08 UTC
<I am online and behind corporate proxy. If I make the "http.systemCertificates": True, then the sign in triggers to open a browser and let me log in from there but VS code doesnt do anything and says that I am offline. If I  change "http.systemCertificates": false, then it simply gives the below notification and does nothing

I tried nslookup login.microsoftonline.com and I could see Server and Address with something like,
Non-authoritative answer:
Name,
Addresses,
Aliases.

Also Settings from VS code looks like below,

 "http.proxy": "http://<<classified>>:8080",
    "settingsSync.ignoredSettings": [
        "-http.systemCertificates"
    ],
    "http.proxyAuthorization": null,
    "azure.tenant": "",
    "azure.cloud": "AzureCloud",
    "http.systemCertificates": false
} 

Does this occur consistently? <Yes>
Repro steps:

1. Attempt signing to Azure extension by typeing CTRL+Shift+P
2.You appear to be offline. Please check your network connection.

Action: azure-account.loginToCloud
Error type: Error
Error Message: No response from the server

Version: 0.11.3
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:865070
extension.bundle.js:2:878103extension.bundle.js:2:878103
```

</details>

**Comment by alexweininger** [comment] 2023-03-22 16:12
The steps for a workaround other users have used are:
1. Disable the `http.systemCertificates` setting
2. Close and reopen VS Code
3. Login
4. Enable the `http.systemCertificates` setting
5.  Close and reopen VS Code

I know you've already explored turning `http.systemCertificates` off, but please try these exact steps and let us know if those work.

Duplicate of https://github.com/microsoft/vscode-azure-account/issues/733

**Comment by kevinblumenfeld** [comment] 2023-03-22 17:16
This has been occurring to me also for nearly 2 weeks, the only thing that works is 
```
"http.systemCertificates": false
```
This does not work for me:

> 1.     Disable the http.systemCertificates setting
> 2.     Close and reopen VS Code
> 3.     Login
> 4.     Enable the http.systemCertificates setting
> 5.     Close and reopen VS Code
>

**Comment by alexweininger** [comment] 2023-03-22 17:18
@kevinblumenfeld, do you encounter this error every time you try and use the extension? Or did setting `"http.systemCertificates": false` fix it for good?

**Comment by kevinblumenfeld** [comment] 2023-03-22 17:35
@alexweininger I just noticed your other question. Yes it was every time I tried to use that extension. It left me unable to use my VSCode as I needed that extension so often. I had to spin up a VM in Azure.

**Comment by SujjithS** [comment] 2023-03-23 03:49
> one point the proxy was even bypassed by I.T. to test if

**Step 1:Disable the http.systemCertificates setting**

- Unchecked the System Certificates from proxy settings.

**Step 2:Close and reopen VS Code**

- Done

**Step 3: Login.**

- CTRL + Shift + P ==>> Azure Sign in
- I could see two pop ups
Pop ups,
- You appear to be offline. Please check your network connection.
- Signing in to Azure...(Dint kick start the browser)

**Step 4: Enable the http.systemCertificates setting**

- Checked the System Certificates from proxy settings.
- It started the browser and prompted to pick a Microsoft account to login
- Clicked on my account==>> It said "You are signed in now and can close this page."
- Went back to VS code app.
- Observed the Signing in to Azure pop up was gone but nothing happened. (You appear to be offline pop up was still there)

**Comment by alexweininger** [comment] 2023-05-09 22:49
Another user posted a [workaround](https://github.com/microsoft/vscode-azure-account/issues/792#issuecomment-1540127373) for the self signed certificate in certificate chain issue on Windows.

Install the [win-ca extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca), which makes Trusted Root Certificates on Windows available to VSCode extensions.

**Closed** 2023-05-24 05:33 UTC
Labels: info-needed, proxy

**Comment by edison-orium** [comment] 2023-05-25 13:45
RE-OPEN!
