### ISSUE TITLE
Azure: Open Powershell in Cloudshell stopped working

### ISSUE THREAD

**Issue by daniel-refahi** [microsoft/vscode-azure-account#235] opened 2020-11-19 07:54 UTC
it simply stopped showing my directory on both windows and mac

![image](https://user-images.githubusercontent.com/5209991/99637178-36530600-2a90-11eb-9fda-f73321ebd879.png)

**Comment by RMacfarlane** [comment] 2021-02-25 00:23
Duplicate of https://github.com/microsoft/vscode-azure-account/issues/231

**Closed by RMacfarlane** 2021-02-25 00:23 UTC
