### ISSUE TITLE
Azure SignIn doesnot work from VS Code - OAuth2Client: ERROR: No response from Server

### ISSUE THREAD

**Issue by srikkar** [microsoft/vscode-azure-account#552] opened 2022-04-21 02:59 UTC
Does this occur consistently? Yes
Repro steps:
1. Azure Sign In from VS Code

Action: azure-account.login
Error type: Error
Error Message: No response from the server

Version: 0.10.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.0
Language: en

<details>
<summary>Call Stack</summary>

```
Logger.createError extension.bundle.js:2:788524
extension.bundle.js:2:801557extension.bundle.js:2:801557
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by srikkar** [comment] 2022-04-21 03:08
Additional Logs
Thu, 21 Apr 2022 03:05:51 GMT:d846f39a-6c0f-4afa-8629-001df25b141a - `OAuth2Client`: ERROR: No response from the server
Stack:
Error: No response from the server
	at Logger.createError (c:\Users\xxxx\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:788524)
	at c:\Users\xxxxx\.vscode\extensions\ms-vscode.azure-account-0.10.0\dist\extension.bundle.js:2:801557
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: No response from the server
Error: No response from the server

**Comment by wwlorey** [comment] 2022-04-21 17:17
Thanks for filing, @srikkar. Please see https://github.com/microsoft/vscode-azure-account/issues/550#issuecomment-1105482177 for guidance and please add any more info you may have on that issue.

It's also possible that the login service or our redirect server was temporarily down.

Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/550.

**Closed by wwlorey** 2022-04-21 17:17 UTC
