### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by MartinTrat** [Microsoft/vscode-azure-account#128] opened 2019-02-01 23:41 UTC
Hi,
when using Azure Account extension in VS Code, I get the error "You appear to be offline. Please check your network connection."
Had Microsoft people over at my company and I would really like to use this extension.

I am behind a corporate proxy, http_proxy in VS Code is set, Windows 10, azure account latest
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment] 2019-02-04 07:58
Duplicate of #121

**Closed by chrmarti** 2019-02-04 07:58 UTC
