### ISSUE TITLE
vscode-azure-account-edit

### ISSUE THREAD

**Issue by wldstudio** [microsoft/vscode-azure-account#557] opened 2022-04-24 17:35 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-account.selectSubscriptions
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.10.1
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
b.toConfigurationEditingError workbench.desktop.main.js:2611:12734
b.updateConfiguration workbench.desktop.main.js:2611:9402
b.doWriteConfiguration workbench.desktop.main.js:2611:9244
async Object.factory workbench.desktop.main.js:2611:8904
```

</details>

**Comment by wwlorey** [comment] 2022-04-25 18:23
Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/556.

Please see https://github.com/microsoft/vscode-azure-account/issues/556#issuecomment-1108894979.

**Closed by wwlorey** 2022-04-25 18:23 UTC
