### ISSUE TITLE
Not able to create azure function

### ISSUE THREAD

**Issue by kirandeep123** [microsoft/vscode-azure-account#774] opened 2023-04-06 07:22 UTC
Does this occur consistently? Yes
Repro steps:

1. use command+shift+P to select Azure Functions: create a function app in azure
2. enter unique name for the function
3. select Node.js 18

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.3
OS: darwin
OS Release: 21.1.0
Product: Visual Studio Code
Product Version: 1.77.1
Language: en

**Comment by alexweininger** [comment] 2023-04-06 17:41
Closing as a duplicate of #614

**Closed by alexweininger** 2023-04-06 17:41 UTC
