### ISSUE TITLE
Cannot login via VSCode

### ISSUE THREAD

**Issue by 0m4r** [microsoft/vscode-azure-account#466] opened 2022-02-19 15:06 UTC
Does this occur consistently? YES
Repro steps:

1. cmd + shift + p -> Azure: sign in
 <img width="626" alt="image" src="https://user-images.githubusercontent.com/451638/154806472-ee279409-af60-4823-a2fe-8921c9731d01.png">

2. browsers open
3. login -> "You are signed in now and can close this page."
4. go back to VSCode and I am not logged in

Action: azure-account.login
Error type: invalid_grant
Error Message: invalid_grant: redacted:id - [redacted:id redacted:id24Z]: AADSTS500202: User account '{EmailHidden}' from external identity provider redacted:url is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id24Z - Correlation ID: redacted:id - Trace ID: redacted:id

Version: 0.10.0
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code - Insiders
Product Version: 1.65.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ServerError.AuthError [as constructor] extension.bundle.js:2:154585
new ServerError extension.bundle.js:2:210448
ResponseHandler.validateTokenResponse extension.bundle.js:2:229292
AuthorizationCodeClient.<anonymous> extension.bundle.js:2:235023
step extension.bundle.js:2:147853
Object.next extension.bundle.js:2:147958
fulfilled extension.bundle.js:2:146622
```

</details>

**Comment by SaleenTheGod** [comment] 2022-02-19 22:38
think i am having this issue as well. Without getting too personal, is this from a company mac and do you all utilize a Proxy?

**Comment by 0m4r** [comment] 2022-02-20 08:04
> think i am having this issue as well. Without getting too personal, is this from a company mac and do you all utilize a Proxy?

I have both 😂
So, i have a company laptop where I use my company account. Here all seems to work.

Then, I have a private laptop where I use a private account.
Here it stopped working.

But know you say this, i recently "bound" my private and company addresses for an microsoft azure cert exam... could this be the problem?

**Comment by wwlorey** [comment] 2022-02-20 22:21
Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/446. Please see https://github.com/microsoft/vscode-azure-account/issues/446#issuecomment-1042243436 for why this error is happing & the workaround for it.

**Closed by wwlorey** 2022-02-20 22:21 UTC
