### ISSUE TITLE
Unable to sign in to Azure local proxy not rerouting?

### ISSUE THREAD

**Issue by FilBot3** [microsoft/vscode-azure-account#217] opened 2020-08-24 16:55 UTC
# The Problem

I am using Visual Studio Code 1.48.0 on Fedora 32 Workstation with the Azure Tools extension for VS Code. I installed VS Code through the RPM repository provided by Microsoft.  

When I click on `Sign in to Azure...`, a browser tab is opened, and it seems to be opening a local proxy that should direct to Azure. This seems very similar to what `kubectl` does where it opens a proxy to the Kubernetes instance you're wanting. However, this doesn't seem to redirect, or open anything and eventually times out.

This is an example of the URL that is provided:

* `http://localhost:38341/signin?nonce=+Eb3FzPvUZgGQY6grWG7pg==`

# The Question

Is there something I should be looking at? Do I need to set `firewall-cmd` so that it allows that port? If that's the case, then why would kubectl work then? 

# Information

## Visual Studio Code information

```
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.16-200.fc32.x86_64
```

## Fedora 32 Workstation information

```bash
cat /etc/*release
Fedora release 32 (Thirty Two)
NAME=Fedora
VERSION="32 (KDE Plasma)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)
```

## Visual Studio Code Extension: Azure Tools

* https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-node-azure-pack

## Visual Studio Code RPM repository

```ini
cat /etc/yum.repos.d/vscode.repo
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

**Comment by jungaretti** [comment] 2020-09-22 01:46
This looks like the same bug as #179

**Comment by FilBot3** [comment] 2020-09-23 16:10
What is the device code option?

**Comment by jungaretti** [comment] 2020-09-30 15:58
@FilBot3 it's a different command that you can use as a temporary workaround to this issue

**Comment by phil-w** [comment] 2021-05-21 13:38
Can someone explain how to use the temporary command?

**Comment by wwlorey** [comment] 2021-07-09 20:31
Closing as duplicate of https://github.com/microsoft/vscode-azure-account/issues/179

**Closed by wwlorey** 2021-07-09 20:31 UTC
