### ISSUE TITLE
Pop up messages about failed Azure Extension  

### ISSUE THREAD

**Issue by arshvin** [microsoft/vscode-azure-account#743] opened 2023-03-18 00:26 UTC
Does this occur consistently?  No
Repro steps:
1. Open VSCode
2. Goto Azure extension button on lefthand side panel
3. Try to open resources under available subscription
4. See the windows messages on right-bottom corner of the screen 
![image](https://user-images.githubusercontent.com/1384989/226073017-72a10906-d558-452e-9d35-869d5687ead3.png)
 

Action: azure-account.initialize
Error type: Error
Error Message: UNIX[No such file or directory]

Version: 0.11.3
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

**Comment by alexweininger** [comment] 2023-03-22 16:14
Thanks for reporting this issue. Closing as a duplicate of https://github.com/microsoft/vscode-azure-account/issues/614. Please follow that issue for updates.

**Closed by alexweininger** 2023-03-22 16:14 UTC
