### ISSUE TITLE
Azure Sign In Does Nothing; Fails silently

### ISSUE THREAD

**Issue by hardik99mehta** [microsoft/vscode-azure-account#615] opened 2022-08-10 07:32 UTC
VS Code details:
Version: 1.67.2 (system setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042

I am working behind the proxy and all other apps connect to internet via the same corporate proxy but not VS Code.
On trying to sign-in to Azure, it tries to authenticate in a browser , it is successful and asks to close the browser. On VS Code , no error is shown and still asks me to sign-in again

Extension version: 0.11.1
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

</details>

**Comment by jt17525** [comment] 2022-08-11 15:41
Whenever you have an opportunity downgrade the plugin to v0.9.11 and test it again. I'm not saying that is the solution tho.

**Comment by jarach** [comment] 2022-08-31 12:45
I'm facing the same issue (also the some outputs in log) - windows + corporate proxy.
Downgrading the azure extensions to versions before from January-March (e.g Azure Account v0.9.11) allowed me to bypass the problem.
Microsoft Azure Storage Explorer - connects to Azure account without problems (the same windows machine + corporate proxy).

**Comment by moyscode** [comment] 2022-09-04 01:30
I am also having this exact issue. As suggested by others, I downgraded the "Azure Account" extension to V0.9.11 & was able to login. However, would appreciate a fix to this in the current version. Thanks.

**Comment by antseng-deloitte** [comment] 2022-12-08 19:23
wow, yeah it worked when I downgrade it to 0.9.11, not sure why the issue is not fixed in the latest version

**Comment by alexweininger** [comment] 2022-12-08 19:28
Are there any errors in the Azure Account output channel when sign-in fails silently on the latest version of the extension?

If possible, could you share the contents of the output channel after it fails?

**Comment by alexweininger** [comment] 2023-01-28 00:39
@hardik99mehta please try the workaround for using a proxy listed in the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy).

**Closed** 2023-02-11 05:33 UTC
Labels: info-needed, proxy
