### ISSUE TITLE
Integrated PowerShell terminal not signed in after Azure Sign In

### ISSUE THREAD

**Issue by mwheatfill** [microsoft/vscode-azure-account#157] opened 2019-10-29 18:42 UTC
When I complete Azure Sign In, the integrated PowerShell terminal does not sign-in to the same account/context. Is this by design?

**Comment by chrmarti** [comment] 2019-10-30 07:26
Currently by design.

**Comment by mwheatfill** [comment] 2019-10-30 16:33
Thanks @chrmarti . My interest piqued after viewing a YouTube video by Sam Cogan who claims to have this experience. https://youtu.be/u8hQyfsRVHA?t=394

It would be a really helpful feature if Azure Sign In was able to pass the credentials to PowerShell to Connect-AzAccount in an existing PowerShell terminal or a new PowerShell terminal. Thanks for flagging as an enhancement. While Cloud Shell is great, I often find myself working on local repos and not wanting to first upload files.

**Comment by wwlorey** [comment] 2021-07-09 21:00
Closing as won't-fix

**Closed by wwlorey** 2021-07-09 21:00 UTC
Labels: enhancement
